-- Create the 'usage' table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.usage (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  credits_used integer,
  user_id uuid,
  CONSTRAINT usage_pkey PRIMARY KEY (id),
  CONSTRAINT usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Enable Row Level Security for the 'usage' table
ALTER TABLE IF EXISTS public.usage ENABLE ROW LEVEL SECURITY;

-- NOTE: For complete RLS policies including INSERT/UPDATE/DELETE,
-- please apply supabase/policies/usage_rls.sql

-- Drop the policy if it exists, then create it
DROP POLICY IF EXISTS "Enable read access for own usage data" ON public.usage;
CREATE POLICY "Enable read access for own usage data"
  ON public.usage
  FOR SELECT
  TO authenticated
  USING ((auth.uid() = user_id));