name: Firebase Daily Backup
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:     # Allows you to run manually
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: firebase login:ci --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Export Firestore
        run: firebase firestore:export ./firestore-backup

      - name: Commit backups
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add firestore-backup
          git commit -m "Automated Firestore backup $(date)" || echo "No changes"
          git push
